stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

GuessNumberTest:
  stage: test
  image: maven:3.8-jdk-11
  script:
    - mvn test -Dtest=GuessNumberTest

Nota Final:
  stage: test
  image: maven:3.8-jdk-11
  script:
    - mvn test -Dtest=GuessNumberTest

